@echo off
echo Activating venv...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements_new.txt --no-cache-dir
echo Running Smart Attendance app with face recognition...
python app.py
pause
